spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/email?createDatabaseIfNotExist=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
spring-doc:
  paths-to-match: /api/**
  swagger-ui:
    use-root-path: true
